Creating full bootstrap project for cloning NEWSWEEK site
rubenpazch/Newsweek-com-Bootstrap- pull request #4
Opened 2020-02-21 21:12 UTC by rubenpazch

This project has different requirements: 

+ Creating a responsive site using bootstrap 4
+ Top bar
+ Features articles 
+ top story
+ culture and travel
+ opinion
+ more stories
+ magazine section
+ featured slider
+ editors pick
+  subscribe and newsletter
+ footer

2020-02-21 23:18 UTC, majovanilla commented
### Code review in progress by Maria Reyes

2020-02-22 00:04 UTC, majovanilla commented
Hey @rubenpazch, 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
I really liked the whole look of the page.

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Check your [HTML validations](https://validator.w3.org/nu/?doc=https%3A%2F%2Fgithub.com%2Frubenpazch%2FNewsweek-com-Bootstrap-%2Fblob%2Fdevelopment%2Findex.html). You have several errors and warnings.

- You need to use bootstrap classes **everywhere** I see that you are taking advantage of the grid classes, but your CSS files have some padding, margin, position and other common classes on bootstrap that you should be using on your HTML. I will point them on separate comments.
This is a Microverse requirement. See screenshot here:
![Screenshot from 2020-02-21 17-38-12](https://user-images.githubusercontent.com/51926937/75080222-0959ce80-54d1-11ea-9a00-d14ec88cd395.png)

- Your page doesn't behave exactly like the original one when you are on small screen sizes. The order of the sections should be: Top story, featured stories, opinion, more stories, culture and travel and latest news. Please make the necessary changes to match this order. I will give one screenshot as an example, but look for all the sections and make sure they are in order.

Your page:
![Screenshot from 2020-02-21 17-46-51](https://user-images.githubusercontent.com/51926937/75080661-3eb2ec00-54d2-11ea-96da-1d75b3f0eb66.png)

Original:
![Screenshot from 2020-02-21 17-47-01](https://user-images.githubusercontent.com/51926937/75080669-45416380-54d2-11ea-9321-e5d18c5cdf02.png)

- Check the More stories section on the small screen size, because it's not behaving like the original one. See screenshots:

Your page:
![Screenshot from 2020-02-21 17-49-14](https://user-images.githubusercontent.com/51926937/75080792-a6693700-54d2-11ea-9d81-1b21ba6e1d82.png)

Original:
![Screenshot from 2020-02-21 17-48-59](https://user-images.githubusercontent.com/51926937/75080767-95b8c100-54d2-11ea-8ba5-7012bada35a4.png)

- The same with the opinion section on small screen sizes. See screenshots:

Your page:
![Screenshot from 2020-02-21 17-51-27](https://user-images.githubusercontent.com/51926937/75080862-e5978800-54d2-11ea-9b45-6a4d0bc86af4.png)

Original:
![Screenshot from 2020-02-21 17-51-33](https://user-images.githubusercontent.com/51926937/75080866-ec25ff80-54d2-11ea-95c5-007fe4376dc9.png)


- Please check the Latest news section also in small screen size.

Your page:
![Screenshot from 2020-02-21 17-52-52](https://user-images.githubusercontent.com/51926937/75080910-1677bd00-54d3-11ea-8464-b61165954746.png)

Original:
![Screenshot from 2020-02-21 17-53-00](https://user-images.githubusercontent.com/51926937/75080916-1bd50780-54d3-11ea-839f-7d76a969879c.png)

- In the magazine section behaves differently on small screens. The title should come after the green picture. Also, check the height of the green picture to fit the original version. 

Your page:
![Screenshot from 2020-02-21 17-54-43](https://user-images.githubusercontent.com/51926937/75081006-58086800-54d3-11ea-87db-4c22552dfcd2.png)

Original:
![Screenshot from 2020-02-21 17-54-35](https://user-images.githubusercontent.com/51926937/75081017-5d65b280-54d3-11ea-9237-e8c2cf3fd279.png)

- The rest of the images on In the magazine section should have a rectangular proportion, yours is a square, please fix that too.

Your page:
![Screenshot from 2020-02-21 17-56-42](https://user-images.githubusercontent.com/51926937/75081114-b6cde180-54d3-11ea-8bda-b3db1b5ebcbe.png)


Original:
![Screenshot from 2020-02-21 17-56-28](https://user-images.githubusercontent.com/51926937/75081124-bd5c5900-54d3-11ea-8a6a-c312db6ee532.png)

- After the In the magazine section comes the featured slideshows and the the Editor's Pick. Your project is in a different order, please address that.

- From all the sections at the end, you have a different image size on the three small images with text. Please adjust them to match the original.

Your page:
![Screenshot from 2020-02-21 18-00-07](https://user-images.githubusercontent.com/51926937/75081250-1fb55980-54d4-11ea-931d-fe074b635d00.png)

Original:
![Screenshot from 2020-02-21 18-00-00](https://user-images.githubusercontent.com/51926937/75081255-247a0d80-54d4-11ea-9101-2d63f1fded00.png)

- The last sections on medium screen sizes are also in the incorrect order and the side images have a different size. Please make them as the original page.

Your page:
![Screenshot from 2020-02-21 18-02-31](https://user-images.githubusercontent.com/51926937/75081334-728f1100-54d4-11ea-91eb-3cb8fddf40d8.png)

Original:
![Screenshot from 2020-02-21 18-02-16](https://user-images.githubusercontent.com/51926937/75081340-7884f200-54d4-11ea-8e43-d07c9d79b959.png)


- Use the hover styling on the footer as the original page.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You don't need to include all the ads on your page, especially when you are in md and sm sizes, because it doesn't look tidy. You could use a bootstrap class to hide them when reaching that screen width. See screenshot below:

YOUR PROJECT:
![Screenshot from 2020-02-21 17-42-01](https://user-images.githubusercontent.com/51926937/75080400-82f1bc80-54d1-11ea-8463-4f01cc8d23b2.png)

ORIGINAL:
![Screenshot from 2020-02-21 17-42-52](https://user-images.githubusercontent.com/51926937/75080448-a1f04e80-54d1-11ea-9249-f419ff12d1fa.png)


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

2020-02-22 00:07 UTC, majovanilla commented on css/style.css
> +  position: relative;
Favor the use of bootstrap classes for positioning.

2020-02-22 00:08 UTC, majovanilla commented on css/style.css
> +  position: absolute;
Favor the use of bootstrap classes for positioning.

2020-02-22 00:08 UTC, majovanilla commented on css/style.css
> +  position: absolute;
Favor the use of bootstrap classes for positioning.

2020-02-22 00:08 UTC, majovanilla commented on css/style.css
> +  padding: 20px 10px 15px;
Favor the use of bootstrap classes for padding.

2020-02-22 00:08 UTC, majovanilla commented on css/style.css
> +  padding: 11px 0 0 0;
Favor the use of bootstrap classes for padding.

2020-02-22 00:09 UTC, majovanilla commented on css/style.css
> +  margin-bottom: 0;
Favor the use of bootstrap classes for margin.

2020-02-22 00:09 UTC, majovanilla commented on css/style.css
> +  margin-bottom: 0;
Favor the use of bootstrap classes for margin.

2020-02-22 00:09 UTC, majovanilla commented on css/style.css
> +  text-align: center;
Favor the use of bootstrap classes for text alignment.

2020-02-22 00:09 UTC, majovanilla commented on css/style.css
> +  width: 396px;
Favor the use of bootstrap classes for width.

2020-02-22 00:09 UTC, majovanilla commented on css/style.css
> +  padding-right: 0;
Favor the use of bootstrap classes.

2020-02-22 00:10 UTC, majovanilla commented on css/style.css
> +  margin: 0 0 0 14px;
Favor the use of bootstrap classes.

2020-02-22 00:10 UTC, majovanilla commented on css/style.css
> +  margin: 0 0 0 14px;
Favor the use of bootstrap classes.

2020-02-22 00:10 UTC, majovanilla commented on css/style.css
> +  text-align: center;
Favor the use of bootstrap classes.

2020-02-22 00:10 UTC, majovanilla commented on css/style.css
> +  padding-top: 15px;
Favor the use of bootstrap classes.

2020-02-22 00:10 UTC, majovanilla commented on css/style.css
> +  padding: 0 10px 0 10px;
Favor the use of bootstrap classes.

2020-02-22 00:11 UTC, majovanilla commented
I left some comments on your code, but there are several classes that you could avoid using while favoring the use of the framework.

2020-02-25 17:40 UTC, rubenpazch commented
thank you for your suggestions, I think I fix it so I'm sending it another time for review

2020-02-25 17:40 UTC, rubenpazch commented
thank you for your suggestions, I think I fix it so I'm sending it another time for review

2020-02-25 17:41 UTC, rubenpazch commented on css/style.css
> +  padding: 0 10px 0 10px;
thank you

2020-02-25 18:32 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :+1:

2020-02-25 19:04 UTC, Oluwadamilareolusakin commented
# Great work making the required changes! @rubenpazch 
You have done really well, however, a new problem has been introduced and your page is scrolling horizontally :frowning: Please look into this and make the adequate corrections! :handshake: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-02-25 19:34 UTC, rubenpazch commented
Thank you for your comments, please can you send me a screenshot.

2020-02-25 20:29 UTC, mosesogwo approved these changes
**Great! Your project is approved:heavy_check_mark:**

You can now merge to master.

**Cheers:stars:**

### Status: Approved!

2020-02-25 20:29 UTC, merged